Models/ErrorViewModel.cs
namespace HomeWork_2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Friend.cs
namespace HomeWork_2.Models
{
    public class Friend
    {
        public int? FriendId { get; set; }
        public string? FriendName { get; set; }

        public string Place { get; set; }


    }
}

Controllers/FriendController.cs
using HomeWork_2.Models;
using Microsoft.AspNetCore.Mvc;

namespace HomeWork_2.Controllers
{
    public class FriendController : Controller
    {
        List<Friend>  Friends;
        
        String StateObject = "";
        
        public IActionResult Index()
        {
            Friends = new List<Friend>
            {
                new Friend() { FriendId = 1, FriendName = "User 1", Place = "close friend"},
                new Friend() { FriendId = 1, FriendName = "User 2", Place = "close friend"},
                new Friend() { FriendId = 1, FriendName = "User 3", Place = "Making friend"},

            };
            
            return View(Friends);
        }

        public IActionResult Create()
        {
            return View();
        }

       
        public IActionResult Edit(Friend friend)
        {
            return View(friend);
        }

        [HttpPost]
        public string SaveChangeFriend(Friend friend)
        {
            //change item in bd
            StateObject = "Object was has saved";
            return StateObject;
        }
        [HttpGet]
        public IActionResult Delete(Friend friend)
        {
            return View(friend);
        }
        
    }
}

Controllers/HomeController.cs
using HomeWork_2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HomeWork_2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Friend/Create.cshtml
@model HomeWork_2.Models.Friend

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Friend</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FriendId" class="control-label"></label>
                <input asp-for="FriendId" class="form-control" />
                <span asp-validation-for="FriendId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FriendName" class="control-label"></label>
                <input asp-for="FriendName" class="form-control" />
                <span asp-validation-for="FriendName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Place" class="control-label"></label>
                <input asp-for="Place" class="form-control" />
                <span asp-validation-for="Place" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Friend/Delete.cshtml
@model HomeWork_2.Models.Friend

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>View</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Friend</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FriendId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FriendId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FriendName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FriendName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Place)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Place)
        </dd>
    </dl>
    
    <form acasp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Friend/Edit.cshtml
@model HomeWork_2.Models.Friend

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>View</h1>

<h4>Friend</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" action="/Friend/SaveChangeFriend">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FriendName" class="control-label"></label>
                <input asp-for="FriendName" class="form-control" />
                <span asp-validation-for="FriendName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Place" class="control-label"></label>
                <input asp-for="Place" class="form-control" />
                <span asp-validation-for="Place" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
            <label class="control-label">.</label>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Friend/Index.cshtml
@model IEnumerable<HomeWork_2.Models.Friend>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FriendId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FriendName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Place)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @if (Model != null)
    {
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FriendId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FriendName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Place)
                </td>
                <td>
                        @Html.ActionLink("Edit", "Edit", item) |
                        @Html.ActionLink("Delete", "Delete", item)
                </td>
            </tr>
        }
    }
    
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeWork_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HomeWork_2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HomeWork_2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Friend" asp-action="Index">Friends</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HomeWork_2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>